### ISSUE TITLE
Destroys the whole asset shape 

### ISSUE THREAD

**Issue by AhmadIzaz** [bramp/nine_patch#2]
So I got the png from your give project 
![textbox_side](https://github.com/bramp/nine_patch/assets/23280743/133ffad3-7b36-465c-830b-99e7bd354a9f)
nad went to this website https://www.9patch.online/editor and created the 9 patch image of this png and this website gives me this 9 slice image 
![textbox_side 9](https://github.com/bramp/nine_patch/assets/23280743/b02329d4-0677-45f1-a9c3-d3579066cac3)
and now when i run
`dart run nine_patcher  path/to/the/.9.png/image` and then it returns this error 

`Unhandled exception:
InvalidNinePatchException: 'No stretch area found along the top.'
#0      findStretch (package:nine_patcher/src/image_decode.dart:115:5)
#1      decodeNinePatchMetadata (package:nine_patcher/src/image_decode.dart:24:19)
#2      new NinePatchImage.fromImage (package:nine_patcher/src/image.dart:18:22)
#3      main (file:///Users/ahmadizaz/.pub-cache/hosted/pub.dev/nine_patcher-1.0.1/bin/nine_patcher.dart:65:29)
<asynchronous suspension>`

Now Okay the error is self explanatory but whatever image I add, it always just gives the error. was not able to create .json file for once.

**Comment by AhmadIzaz** [comment]
Never mind, I used this https://romannurik.github.io/AndroidAssetStudio/nine-patches.html#source.type=image&sourceDensity=640&name=nine_primary_button for creating 9 patch image and then I used dart run nine_patcher and it did created the two files, json and the png file.

**Comment by AhmadIzaz** [comment]
But upon using this 

```
Center(
          child: NinePatchImage.fromAssetMetadata(
              name: 'assets/nine_primary_button.9.json',
              margin: const EdgeInsets.all(5),
              padding: const EdgeInsets.all(5),
              child: const Text('This is my button')),
        ),
```
It destroyed the button :( 

![image](https://github.com/bramp/nine_patch/assets/23280743/44cbcde5-641e-473d-9802-ea1abc55f1a4)

**Comment by AhmadIzaz** [comment]
It does stretch but destroyed the whole button layout

Original png image 
![nine_primary_button](https://github.com/bramp/nine_patch/assets/23280743/5b66997e-055b-4823-9257-00e42c7b1630)

after 

![image](https://github.com/bramp/nine_patch/assets/23280743/3424abd6-8cb5-4d6c-ab8c-0d251b2cb934)

Here is the json

[nine_primary_button.9.json](https://github.com/user-attachments/files/15522092/nine_primary_button.9.json)
